name: "runnersapi"
description: "runners api"
version: "0.0.4"
slug: "runnersapi"
init: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
map:
- config:rw
startup: system

stdin: true
ports:
  3000/tcp: 3000
